// productsData.js
const productsData = {
    Rifle: [
      { id: '2',
        name: 'F2000S',
        image: 'https://upload.wikimedia.org/wikipedia/commons/d/d8/FN_F2000S.JPG',
        description: 'This is a short description of Product 2.',
        price: 1500,
        rating: 4,
      },
      { id: '1',
        name: 'Ak47',
        image: 'https://upload.wikimedia.org/wikipedia/commons/6/65/AK-47_type_II_noBG.png',
        description: 'This is a short description of Product 1.',
        price: 2000,
        rating: 5,
      },
      
      { id: '3',
        name: 'M4',
        image: 'https://upload.wikimedia.org/wikipedia/commons/6/68/PEO_M4_Carbine_RAS_M68_CCO.png',
        description: 'This is a short description of Product 3.',
        discountedPrice: 10,
        price: 1000,
        rating: 3,
      },
      { id: '4',
        name: 'M1Grand',
        image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/M1_Garand_rifle_USA_noBG_new.png/1200px-M1_Garand_rifle_USA_noBG_new.png',
        description: 'This is a short description of Product4.',
        price: 5000,
        rating: 5,
      },
      { id: '5',
        name: 'M1Grand',
        image: '',
        description: 'This is a short description of Product5.',
        price: 5000,
        rating: 5,
      },
      { id: '6',
        name: 'M1Grand',
        image: '',
        description: 'This is a short description of Product6.',
        price: 5000,
        rating: 5,
      },
      { id: '7',
        name: 'M1Grand',
        image: '',
        description: 'This is a short description of Product7.',
        price: 5000,
        rating: 5,
      },
      { id: '8',
        name: 'M1Grand',
        image: '',
        description: 'This is a short description of Product8.',
        price: 5000,
        rating: 5,
      },
      { id: '9',
        name: 'M1Grand',
        image: '',
        description: 'This is a short description of Product9.',
        price: 5000,
        rating: 5,
      },
      { id: '10',
        name: 'M1Grand',
        image: '',
        description: 'This is a short description of Product10.',
        price: 5000,
        rating: 5,
      },
      { id: '11',
        name: 'Uzi',
        image: 'https://cdn.britannica.com/36/125036-050-D680D785/Uzi-submachine-gun.jpg',
        description: 'This is a short description of Product11.',
        price: 2000,
        rating: 5,
      },
      
      
    ],
    // Knife: [
    //   { id: 1, name: 'Product 1' },
    //   { id: 2, name: 'Product 2' },
    //   // Add more products for category2
    // ],
    Pistol: [
      { id: '1', 
        name: 'Product 1',
        price: 1200,
        image: '',
        description:'',
        
        rating: 2,

      },
      {  id: '2', 
        name: 'Product 2',
        price: 1300,
        image: '',
        description:'',
        
        rating: 2,
      },
      // Add more products for category2
    ],
    
  };
  
export default productsData;
  